apiVersion: starburstdata.com/v1
kind: Presto
metadata:
  name: starburst-demo
spec:
  nameOverride: starburst-demo
  memory:
    nodeMemoryHeadroom: 1Gi
  coordinator:
    cpuRequest: ""
    memoryAllocation: ""
  worker:
    count: 2
    prestoWorkerShutdownGracePeriodSeconds: 1
    cpuRequest: ""
    memoryAllocation: ""
  hive:
    internalMetastore:
      image:
        pullPolicy: Always
      internalPostgreSql:
        enabled: true
      memory: 0.5Gi
      cpu: 0.5
